import { Genre } from '@/types';

export const GENRES: Genre[] = [
  {
    id: 'vaporwave',
    name: 'Vaporwave',
    subreddit: 'Vaporwave',
    description: 'Aesthetic electronic music with 80s/90s samples',
    icon: '🌴',
    color: '#ff71ce',
  },
  {
    id: 'synthwave',
    name: 'Synthwave',
    subreddit: 'synthwave',
    description: 'Retro 80s inspired electronic music',
    icon: '🌆',
    color: '#01cdfe',
  },
  {
    id: 'lofi',
    name: 'Lo-Fi Hip Hop',
    subreddit: 'LofiHipHop',
    description: 'Chill beats to relax/study to',
    icon: '☕',
    color: '#b967ff',
  },
  {
    id: 'chillwave',
    name: 'Chillwave',
    subreddit: 'chillwave',
    description: 'Dreamy, nostalgic electronic pop',
    icon: '🌊',
    color: '#fffb96',
  },
  {
    id: 'electronicmusic',
    name: 'Electronic',
    subreddit: 'electronicmusic',
    description: 'All genres of electronic music',
    icon: '⚡',
    color: '#05ffa1',
  },
  {
    id: 'futurebeats',
    name: 'Future Beats',
    subreddit: 'futurebeats',
    description: 'Experimental electronic and hip-hop',
    icon: '🔮',
    color: '#ff6b6b',
  },
  {
    id: 'listentothis',
    name: 'Listen To This',
    subreddit: 'listentothis',
    description: 'Discover new and overlooked music',
    icon: '🎵',
    color: '#4ecdc4',
  },
  {
    id: 'indieheads',
    name: 'Indie',
    subreddit: 'indieheads',
    description: 'Indie rock and alternative music',
    icon: '🎸',
    color: '#f7dc6f',
  },
  {
    id: 'metal',
    name: 'Metal',
    subreddit: 'Metal',
    description: 'Heavy metal in all its forms',
    icon: '🤘',
    color: '#8e44ad',
  },
  {
    id: 'hiphopheads',
    name: 'Hip Hop',
    subreddit: 'hiphopheads',
    description: 'Hip hop music and culture',
    icon: '🎤',
    color: '#e74c3c',
  },
  {
    id: 'jazz',
    name: 'Jazz',
    subreddit: 'Jazz',
    description: 'Jazz music from all eras',
    icon: '🎷',
    color: '#3498db',
  },
  {
    id: 'ambient',
    name: 'Ambient',
    subreddit: 'ambientmusic',
    description: 'Atmospheric and ambient soundscapes',
    icon: '🌙',
    color: '#1abc9c',
  },
  {
    id: 'dnb',
    name: 'Drum & Bass',
    subreddit: 'DnB',
    description: 'High-energy drum and bass music',
    icon: '🥁',
    color: '#e67e22',
  },
  {
    id: 'techno',
    name: 'Techno',
    subreddit: 'Techno',
    description: 'Electronic dance music',
    icon: '🔊',
    color: '#9b59b6',
  },
  {
    id: 'postrock',
    name: 'Post-Rock',
    subreddit: 'postrock',
    description: 'Experimental and atmospheric rock',
    icon: '🎻',
    color: '#34495e',
  },
  {
    id: 'punk',
    name: 'Punk',
    subreddit: 'punk',
    description: 'Punk rock and its subgenres',
    icon: '💀',
    color: '#c0392b',
  },
];

export const DEFAULT_GENRE = GENRES[0];

export const SORT_OPTIONS = [
  { value: 'hot', label: 'Hot' },
  { value: 'new', label: 'New' },
  { value: 'top', label: 'Top' },
  { value: 'rising', label: 'Rising' },
] as const;

export const TIME_FILTERS = [
  { value: 'hour', label: 'Hour' },
  { value: 'day', label: 'Day' },
  { value: 'week', label: 'Week' },
  { value: 'month', label: 'Month' },
  { value: 'year', label: 'Year' },
  { value: 'all', label: 'All Time' },
] as const;
